---
title: "Lab 10 Graphs"
author: "Benjamin Rogers"
date: "5/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
bibentry(bibliography.bib)
```
```{r, message= FALSE, warning= FALSE}
library(tidyverse)
library(maps)
library(mapdata)
library(lubridate)
library(viridis)
library(wesanderson)
library(RColorBrewer)

```
Most of my family lives in Louisiana, so I chose to plot the data for Louisiana

```{r, echo=FALSE, results=TRUE, message=FALSE, warning=FALSE}

daily_report <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Province_State == "Louisiana") %>% 
  group_by(Admin2) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Admin2 = tolower(Admin2))
us <- map_data("state")
Louisiana_us <- subset(us, region == "louisiana")
counties <- map_data("county")
louisiana_county <- subset(counties, region == "louisiana")
state_join <- left_join(louisiana_county, daily_report, by = c("subregion" = "Admin2")) 

ggplot(data = louisiana_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 

  geom_polygon(data = state_join, aes(fill = Confirmed), color = "white") +
  scale_fill_gradientn(colors = brewer.pal(n = 5, name = "BuGn"),
                       trans = "log10") +
  labs(title = "COVID-19 Confirmed Cases in Louisiana'")
```

An Interactive plot of confirmed cases in Louisiana with hover for info:
```{r, echo=FALSE, results=TRUE, message=FALSE, warning=FALSE}
library(plotly)
library(wesanderson)
ggplotly(
  ggplot(data = louisiana_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 

  geom_polygon(data = state_join, aes(fill = Confirmed), color = "black") +
    scale_fill_gradientn(colours = 
                         wes_palette("Zissou1", 100, type = "continuous")) +
  ggtitle("COVID-19 Cases in Louisiana") +

  labs(x=NULL, y=NULL) +
  theme(panel.border = element_blank()) +
  theme(panel.background = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.text = element_blank())
)
```


```{r, echo=FALSE, results=TRUE, message=FALSE, warning=FALSE}
time_series_confirmed_long <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")  %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Confirmed") 
# Let's get the times series data for deaths
time_series_deaths_long <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")  %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Deaths")
time_series_recovered_long <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region") %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Recovered")
# Create Keys 
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)
time_series_recovered_long <- time_series_recovered_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Recovered)
# Join tables
time_series_long_joined <- full_join(time_series_confirmed_long,
                                     time_series_deaths_long, by = c("Key"))
time_series_long_joined <- full_join(time_series_long_joined,
                                     time_series_recovered_long, by = c("Key")) %>% 
  select(-Key)
# Reformat the data
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
# Create Report table with counts
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
library(ggplot2)
library(gganimate)
library(transformr)
theme_set(theme_bw())
data_time <- time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths", "Recovered"), sum) %>% 
  filter (Country_Region %in% c("China","France","Norway","Italy","US")) 
p <- ggplot(data_time, aes(x = Date,  y = Confirmed, color = Country_Region)) + 
  geom_point() +
  geom_line() +
  ggtitle("Confirmed COVID-19 Cases") +
  geom_point(aes(group = seq_along(Date))) +
  transition_reveal(Date) 

animate(p, end_pause = 15)
```
